### ISSUE TITLE
靜態網頁產生 script 

### ISSUE THREAD

**Issue by pofeng** [ocftw/ocf.tw#18]
目前 ocf.tw 還是希望以靜態網頁為主, 但是需要搭配一個產生網頁的 script 

很初步的想法在這裡 
https://github.com/ocftw/ocf.tw/tree/gh-pages/t

index.raw.html 標註 {{footer}} , go.sh 就把 
index.raw.html 和 footer.html 合併變成 index.html

**Comment by bobchao** [comment]
這現在應該算解決了？ （有 template engine）

**Comment by pofeng** [comment]
對, 來關

**Comment by pofeng** [comment]
用 github pages ,內建的 Jekyll
https://ocf-tw.hackpad.com/F6C2l8Z0B5J
