### ISSUE TITLE
好像是 CSS 問題

### ISSUE THREAD

**Issue by pofeng** [ocftw/ocf.tw#23]
@bobchao 你上次有改哪部份, 可能會造成下圖問題嗎 ?

( url: http://ocf.tw/events/elc2015/ ) 

![1](https://cloud.githubusercontent.com/assets/43583/7786335/33a6fc20-01f8-11e5-923d-85f8b7319e8a.PNG)

**Comment by bobchao** [comment]
沒有，看起來是 KKTIX 的問題 orz

On 24 May 2015 at 09:36, Pofeng Lee notifications@github.com wrote:

> @bobchao https://github.com/bobchao 你上次有改哪部份, 可能會造成下圖問題嗎 ?
> 
> ( url: http://ocf.tw/events/elc2015/ )
> 
> [image: 1]
> https://cloud.githubusercontent.com/assets/43583/7786335/33a6fc20-01f8-11e5-923d-85f8b7319e8a.PNG
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ocftw/ocf.tw/issues/23.

## 

Po-chiang Chao  (:BobChao)
Mozillian and Creative Commoner, Taiwan
http://twitter.com/bobchao http://blog.bobchao.net/

**Comment by bobchao** [comment]
我從 KKTIX 那邊找到問題來源了 通報中

**Comment by pofeng** [comment]
:+1:

**Comment by pofeng** [comment]
KKTIX 應該修正了
